default_install_hook_types:
  - pre-commit
  - commit-msg

default_stages:
  - pre-commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 2c9f875913ee60ca25ce70243dc24d5b6415598c # v4.6.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: trailing-whitespace

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 772d7ffaeee5d611a904cc564a3fe3c7ad927635 # v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: d0bcdb35c6999a4a120b528f050d2b11778fd3d0 # v0.1.23
    hooks:
      - id: shellcheck

  - repo: https://github.com/hadolint/hadolint
    rev: b3555ba9c2bfd9401e79f2f0da68dd1ae38e10c7 # v2.12.0
    hooks:
      - id: hadolint
