---
name: Build

on:
  workflow_call:
    inputs:
      godotVersion:
        type: string
        required: true
      exportPlatform:
        type: string
        required: true
      dotNet:
        type: boolean
        required: true

  workflow_dispatch:
    inputs:
      godotVersion:
        type: string
        required: true
      exportPlatform:
        type: string
        required: true
      dotNet:
        type: boolean
        required: true

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7


      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4 # v3.4.0


      - name: Get Tag
        id: get-tag
        run: |
          if [ "${{ inputs.dotNet }}" == "true" ]; then
            echo "tag=ghcr.io/${{ github.repository }}:${{ inputs.godotVersion }}-dotnet-${{ inputs.exportPlatform }}" > "$GITHUB_OUTPUT"
          else
            echo "tag=ghcr.io/${{ github.repository }}:${{ inputs.godotVersion }}-${{ inputs.exportPlatform }}" > "$GITHUB_OUTPUT"
          fi


      - name: Build Docker Image
        uses: docker/build-push-action@1a162644f9a7e87d8f4b053101d1d9a712edc18c # v6.3.0
        with:
          load: true
          context: src
          cache-from: type=registry,ref=${{ steps.get-tag.outputs.tag }}-buildcache
          build-args: |
            GODOT_VERSION=${{ inputs.godotVersion }}
            EXPORT_PLATFORM=${{ inputs.exportPlatform }}
            DOTNET=${{ inputs.dotNet }}
          tags: |
            ${{ steps.get-tag.outputs.tag }}


      - name: Test Docker Image
        run: docker run --rm --mount type=bind,source=.,target=/github/home --workdir /github/home ${{ steps.get-tag.outputs.tag }} test.sh ${{ inputs.exportPlatform }}


      - name: Login to GitHub Container Registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Push Docker Image
        uses: docker/build-push-action@1a162644f9a7e87d8f4b053101d1d9a712edc18c # v6.3.0
        with:
          push: true
          context: src
          cache-to: type=registry,ref=${{ steps.get-tag.outputs.tag }}-buildcache,mode=max
          build-args: |
            GODOT_VERSION=${{ inputs.godotVersion }}
            EXPORT_PLATFORM=${{ inputs.exportPlatform }}
            DOTNET=${{ inputs.dotNet }}
          tags: |
            ${{ steps.get-tag.outputs.tag }}
