---
name: Lint

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'workflow_dispatch' }}
  VALIDATE_BASH: true
  VALIDATE_EDITORCONFIG: true
  VALIDATE_GITHUB_ACTIONS: true
  VALIDATE_JSON: true
  VALIDATE_MARKDOWN: true
  VALIDATE_YAML: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Super Linter
        uses: super-linter/super-linter@3fe03abab2eafb293ace16d4a3b07aeabcb3f1a0 # v6.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
